
import React from 'react';
import { 
  CheckCircle2, 
  ExternalLink, 
  Gift, 
  Users, 
  Key, 
  User, 
  Copy, 
  Search, 
  Filter, 
  Settings2,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  MoreVertical,
  ChevronRight,
  TrendingUp,
  LayoutGrid,
  Pencil,
  X,
  ArrowUp,
  Trash2,
  Check,
  Home,
  Mail,
  Share2,
  AlertTriangle,
  AlertCircle
} from 'lucide-react';

export const Icons = {
  SignedUp: CheckCircle2,
  Link: ExternalLink,
  Bonus: Gift,
  Referral: Users,
  Credentials: Key,
  Account: User,
  Copy: Copy,
  Search: Search,
  Filter: Filter,
  Config: Settings2,
  Lock: Lock,
  Unlock: Unlock,
  Show: Eye,
  Hide: EyeOff,
  Menu: MoreVertical,
  Next: ChevronRight,
  Daily: TrendingUp,
  Grid: LayoutGrid,
  Edit: Pencil,
  Clear: X,
  Top: ArrowUp,
  Trash: Trash2,
  Check: Check,
  Home: Home,
  Focus: Mail,
  Share: Share2,
  Alert: AlertTriangle,
  Error: AlertCircle
};
